/// <reference types="vite/client" />

interface ImportMetaEnv {
    // Auto-generated by `npx vite-envs update-types`
    readonly TITLE: string;
    readonly CUSTOM_META: string;
}
interface ImportMeta {
    readonly env: ImportMetaEnv;
}
