/// <reference types="vite-envs/client" />
type ImportMetaEnv = {
  // Auto-generated by `npx vite-envs update-types`
  BASE_URL: string
  MODE: string
  DEV: boolean
  PROD: boolean
  TITLE: string
  CUSTOM_META: string
}
interface ImportMeta {
  url: string

  readonly hot?: import('vite-envs/types/hot').ViteHotContext

  readonly env: ImportMetaEnv

  glob: import('vite-envs/types/importGlob').ImportGlobFunction
}
